version: '2'
services:
    estudiantes-api:
        build: .
        image: estudiantes-api
        environment:
            - NODE_ESTUDIANTE=dev
            - NODE_ESTUDIANTE_HOST=estudiantes-mysql
            - NODE_ESTUDIANTE_DB=inscripciones
            - NODE_ESTUDIANTE_USER=plataforma
            - NODE_ESTUDIANTE_PASSWORD=plataforma
            - NODE_ESTUDIANTE_DBPORT=3306
            - SERVER_WS_DOCENTES=http://localhost:8082/docentesSoap?wsdl
        ports:
            - "8081:8081"        
    estudiantes-mysql:
     extends:
        file: mysql.yml
        service: estudiantes-mysql
